# Build settings
# Gems
gems:
- jekyll-paginate
- jekyll-feed

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are hosting it on Github for some project with name 'projectname', then the url and baseurl should look like:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"
url: "https://epfllibrary.github.io/infoscience-map"
enforce_ssl: ""
baseurl: "/infoscience-map"

# Title of website
title: INFOSCIENCE Metadata profile

#Default keywords (used if no keywords are specified on a page basis)
keywords: dspace-cris, EPFL, metadata application profile

# Short description of your site
desc: "This is the metadata application profile for Infoscience, the EPFL institutional repository."

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/epfl.svg"

# List of links in the navigation bar
nav-links:
  Home: ""
  # Guidelines: "guidelines"
  About: "about"
  Contact: "contact"

# --- Footer options --- #

# If the values are empty, they are ignored
profile:
  name: Infoscience Support
  email: infoscience@epfl.ch
  # facebook: your-fb-id
  github: epfllibrary
  # twitter: your-twitter-id
  # linkedin: your-linkedin-id
  # stackoverflow: your-stackoverflow-id

# To display link in the footer section
# pretty-url: "bchetty.com"

# --- Misc --- #

# Google Analytics Settings
# google_analytics: "Your-GA-Id"

# Set these options as you need (For more information, check Jekyll's site)
timezone: "Europe/Zurich"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

created-by: Julien, Sicot
creator-url: https://people.epfl.ch/julien.sicot
