label: Application number
label-fr: Demande
name: dc_identifier_applicationnumber
schema: dc
dc-element: identifier
dc-qualifier: applicationnumber
definition: Patent application number.
obligation: optional
type: descriptive
repeatable: 'true'
legacy_marc: null
indexes:
- configuration: researchoutputs
  indexes:
  - dc.identifier.applicationnumber
range:
- label: String
  uri: null
  values:
  - ''
