label: Application number
label-fr: Demande
name: dc_identifier_applicationnumber
schema: dc
dc-element: identifier
dc-qualifier: applicationnumber
definition: Description coming soon...
obligation: optional
type: descriptive
repeatable: 'true'
legacy_marc: ''
indexes:
- configuration: researchoutputs
  indexes:
  - dc.identifier.applicationnumber
range:
- label: String
  uri: ''
  values:
  - ''
